---
# Manages NGINX configuration
- name: Create default configuration
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify:
    - Restart NGINX service

- name: Create default home page
  copy:
    src: index.html
    dest: /usr/share/nginx/index.html
