---
- hosts: all
  become: yes
  tasks:
    - group:
        name: devops
        state: present

    - name: Create devops sudo user
      user:
        name: devops
        comment: 'devops user'
        uid: 2001
        group: devops

    - name: Install htop
      apt:
        name: htop
        state: present
        update_cache: yes

- hosts: www
  become: yes
  tasks:
    - name: Add official nginx repository
    apt_repository:
      repo: 'deb http://nginx.org/packages/ubuntu/ lucid nginx'

    - name: Install nginx web server and ensure latest version
      apt:
        name: nginx
        state: latest

    - name: Start nginx service
      service:
        name: nginx
        state: started
